name: MoneyGive
version: '${version}'
main: net.fukumaisaba.moneygive.MoneyGive
api-version: 1.19

depend:
  - Vault

softdepend:
  - Vault
  - iConomy

permissions:
  moneygive:
    .description: ""
    children:
      moneygive.commands: true

  moneygive.commands:
    description: ""
    children:
      moneygive.commands.moneygive:
        description: ""
        default: not op
      moneygive.commands.reload:
        description: ""
        default: op